language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - pypy

install:
  - pip install -r requirements.txt
  - pip install zetup[commands]
  - zetup install
  - pip install pytest
  - pip install tox

script:
  - zetup pytest
  - py.test -v test/
  - zetup tox
